stages:
  - build
  - deploy
  - cleanup

before_script:
  - source "$(~/bin/trdl use werf 1.2 stable)"
  - type werf && source $(werf ci-env gitlab --as-file)
  - export WERF_SECRET_KEY=$WERF_SECRET_KEY

Build and Publish:
  stage: build
  script:
    - werf build
  except: [schedules]
  only:
    - rc
  tags:
    - werf


Deploy to Develop:
  stage: deploy
  script:
    - werf converge --env=itsm-develop --kube-context="default/dev" --skip-build --secret-values=.helm/dev-secret-values.yaml
  dependencies:
    - Build and Publish
  except: [schedules]
  tags:
    - werf
  only:
    - rc

Cleanup:
  stage: cleanup
  script:
    - werf cleanup --kube-context="default/dev"
  only: [schedules]
  tags:
    - werf