stages:
  - test
  - build
  - deploy
  - cleanup

Tests:
  stage: test
  image: node:18-buster
  script:
    - export REACT_APP_API_URL=http://localhost:3000
    - export REACT_APP_ENVIRONMENT=test
    - export CI=true
    - yarn install
    - yarn test
  only:
    - rc
  tags:
    - docker


Build and Publish:
  stage: build
  before_script:
    - source "$(~/bin/trdl use werf 1.2 stable)"
    - type werf && source $(werf ci-env gitlab --as-file)
    - export WERF_SECRET_KEY=$WERF_SECRET_KEY
  script:
    - werf build
  except: [schedules]
  only:
    - rc
  tags:
    - werf


Deploy to Develop:
  stage: deploy
  before_script:
    - source "$(~/bin/trdl use werf 1.2 stable)"
    - type werf && source $(werf ci-env gitlab --as-file)
    - export WERF_SECRET_KEY=$WERF_SECRET_KEY
  script:
    - werf converge --env=itsm-develop --kube-context="default/dev" --skip-build --secret-values=.helm/dev-secret-values.yaml
  dependencies:
    - Build and Publish
  except: [schedules]
  tags:
    - werf
  only:
    - rc

Cleanup:
  stage: cleanup
  before_script:
    - source "$(~/bin/trdl use werf 1.2 stable)"
    - type werf && source $(werf ci-env gitlab --as-file)
    - export WERF_SECRET_KEY=$WERF_SECRET_KEY
  script:
    - werf cleanup --kube-context="default/dev"
  only: [schedules]
  tags:
    - werf