stages:
  - lint
  - test
  - build
  - deploy
  - cleanup

Lint:
  stage: lint
  image: jeremymiller/node-lint
  interruptible: true
  script:
    - yarn lint
  only:
    - rc
    - master
    - develop
    - task-20635
  tags:
    - docker

Tests:
  stage: test
  image: node:18-alpine
  interruptible: true
  script:
    - export REACT_APP_API_URL=http://localhost:3000
    - export REACT_APP_ENVIRONMENT=test
    - export CI=true
    - yarn install
    - yarn test
  only:
    - rc
    - master
    - develop
  tags:
    - docker


.base_build: &base_build
  stage: build
  interruptible: true
  before_script:
    - source "$(~/bin/trdl use werf 1.2 stable)"
    - type werf && source $(werf ci-env gitlab --as-file)
    - export WERF_SECRET_KEY=$WERF_SECRET_KEY
  script:
    - werf build --env=$env
  except: [schedules]
  only:
    - rc
    - master
    - develop
    - task-20635
  tags:
    - werf

.base_deploy: &base_deploy
  stage: deploy
  interruptible: true
  before_script:
    - source "$(~/bin/trdl use werf 1.2 stable)"
    - type werf && source $(werf ci-env gitlab --as-file)
    - export WERF_SECRET_KEY=$WERF_SECRET_KEY
  script:
    - werf converge --kube-context="$kube_context" --env=$env --values=.helm/$env-values.yaml --secret-values=.helm/$env-secret-values.yaml
  except: [schedules]
  tags: [werf]


Build for Develop:
  <<: *base_build
  variables:
    env: dev
  only:
    - develop
    - task-20635

Build for Staging:
  <<: *base_build
  variables:
    env: stage
  only:
    - rc


Deploy to Develop:
  <<: *base_deploy
  dependencies:
    - Build for Develop
  variables:
    env: dev
    kube_context: default/dev
  only:
    - develop
    - task-20542

Deploy to Staging:
  <<: *base_deploy
  dependencies:
    - Build for Staging
  variables:
    env: stage
    kube_context: default/dev
  only:
    - rc

Cleanup:
  stage: cleanup
  interruptible: true
  before_script:
    - source "$(~/bin/trdl use werf 1.2 stable)"
    - type werf && source $(werf ci-env gitlab --as-file)
    - export WERF_SECRET_KEY=$WERF_SECRET_KEY
  script:
    - werf cleanup --kube-context="default/dev"
  only: [schedules]
  tags:
    - werf
