stages:
  - lint
  - test
  - build
  - deploy
  - cleanup

Lint:
  stage: lint
  image: node:18-alpine
  interruptible: true
  script:
    - yarn install
    - yarn lint
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/
    policy: pull-push
  only:
    - rc
    - master
    - develop
  tags:
    - docker
    - vk

Tests:
  stage: test
  image: node:18-alpine
  interruptible: true
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - export REACT_APP_API_URL=http://localhost:3000
    - export REACT_APP_ENVIRONMENT=test
    - export CI=true
    - export DEBUG_PRINT_LIMIT=20
    - yarn install
    - yarn test:ci
  cache:
    - key:
        files:
          - package.json
      paths:
        - node_modules/
      policy: pull
  only:
    # - rc
    - master
#    - develop
  tags:
    - docker
    - vk


.base_build: &base_build
  stage: build
  interruptible: true
  before_script:
    - source "$(~/bin/trdl use werf 1.2 stable)"
    - type werf && source $(werf ci-env gitlab --as-file)
    - export WERF_SECRET_KEY=$WERF_SECRET_KEY
  script:
    - werf build --env=$env
  cache:
    - key:
        files:
          - package.json
      paths:
        - node_modules/
      policy: pull
  except: [schedules]
  only:
    - rc
    - master
    - develop
  tags:
    - werf

.base_deploy: &base_deploy
  stage: deploy
  interruptible: true
  before_script:
    - source "$(~/bin/trdl use werf 1.2 stable)"
    - type werf && source $(werf ci-env gitlab --as-file)
    - export WERF_SECRET_KEY=$WERF_SECRET_KEY
  script:
    - werf converge --kube-context="$kube_context" --env=$env --values=.helm/$env-values.yaml --secret-values=.helm/$env-secret-values.yaml
  except: [schedules]
  tags: [werf]


Build for Develop:
  <<: *base_build
  variables:
    env: dev
  only:
    - develop

Build for Staging:
  <<: *base_build
  variables:
    env: stage
  only:
    - rc

Build for Production:
  <<: *base_build
  variables:
    env: prod
  only:
    - master


Deploy to Develop:
  <<: *base_deploy
  dependencies:
    - Build for Develop
  variables:
    env: dev
    kube_context: default/dev
  only:
    - develop

Deploy to Staging:
  <<: *base_deploy
  dependencies:
    - Build for Staging
  variables:
    env: stage
    kube_context: default/dev
  only:
    - rc

Deploy to Production:
  <<: *base_deploy
  when: manual
  dependencies:
    - Build for Production
  variables:
    env: prod
    kube_context: default/production
  only:
    - master

Cleanup:
  stage: cleanup
  interruptible: true
  before_script:
    - source "$(~/bin/trdl use werf 1.2 stable)"
    - type werf && source $(werf ci-env gitlab --as-file)
    - export WERF_SECRET_KEY=$WERF_SECRET_KEY
  script:
    - werf cleanup --kube-context="default/dev"
  only: [schedules]
  tags:
    - werf
