# Secret for access to gitlab docker registry TODO remove after adding kube-replicator
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.global.werf.name }}-dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}