apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.werf.name }}
  labels:
    app: {{ .Values.global.werf.name }}
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: {{ .Values.global.werf.name }}